% Copyright Claudio Menghi, University of Luxembourg, 2018-2019, claudio.menghi@uni.lu  
function isPositive=isrow(inpArray)
isPositive=size(inpArray,1)==1&&...
    numel(inpArray)==length(inpArray)&&...
    ismatrix(inpArray);