package cs.purdue.edu.model;

import java.util.ArrayList;

public abstract class Subject {
	/**
	 * To uniquely identify the subject, generated by concatenating a few fields. Examples are as follows:
	 * 	class: java.util.ArrayList
	 * 	method: java.util.ArrayList.add(int index, E element)
	 * 	field: java.util.ArrayList.elementData
	 * 	parameter: java.util.ArrayList.add(int index, E element).index
	 * 	variable: java.util.ArrayList.remove(int index).oldValue@lineNum (in case multiple variables with the same name)
	 * 	statement: java.util.ArrayList.xx//TODO
	 */
	private String id;
	private int lineNumBegin;
	private int lineNumEnd;
	private String pack;
	private ArrayList<Comment> comments= new ArrayList<Comment>();
	
	public interface subject {
		public static final String cls = "class";
		public static final String field= "field";
		public static final String method = "method";
		public static final String param = "paramater";
		public static final String statement = "statement";
		public static final String var = "variable";
	}
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public int getLineNumBegin() {
		return lineNumBegin;
	}
	public void setLineNumBegin(int lineNumBegin) {
		this.lineNumBegin = lineNumBegin;
	}
	public int getLineNumEnd() {
		return lineNumEnd;
	}
	public void setLineNumEnd(int lineNumEnd) {
		this.lineNumEnd = lineNumEnd;
	}
	public String getPack() {
		return pack;
	}
	public void setPack(String pack) {
		this.pack = pack;
	}
	public ArrayList<Comment> getComments() {
		return comments;
	}
	public void setComments(ArrayList<Comment> comments) {
		this.comments = comments;
	}
	
}
